### ISSUE TITLE
Launch command not working?

### ISSUE THREAD

**Issue by lifeModder19135** [intrinsically/codestar-staruml#1]
I've installed the extensions for both sides, but when I try to launch from VS Code, I am just getting a "no such command" exception. Not sure what I am missing. My VS Code has the CLI set to GIT bash, but I wouldn't think that would make a difference in this case.

 Any help would be much appreciated. Thanks in advance. 

Nate T.

**Comment by intrinsically** [comment]
ah, apologies. i'll have a look at it today, i haven't used it for 18months, it's likely to be that I developed it against an older version of VSCode.

I doubt it's anything to do with GIT bash, the plugin invokes VSCode commands directly.

**Comment by intrinsically** [comment]
Just got it working with Star UML 4.0.1 and VSCode 1.55.2, installing both extensions from their respective app stores.

Here's what i did. I realize you probably did almost identical, just wanted to make sure:

1. installed VSCode codestar extension & restarted. Started with "codestar:star" and pressed enter to get it started on port 8081 when prompted.
2. installed StarUML codestar extension & restarted
3. went to a file in VSCode. Clicked on a class in StarUML and selected the menu option "Save position" (cmd-P)
4. changed file in VSCode, middle clicked on class in StarUML and verified that the previous VSCode file is selected

Can you send me details of what version of the apps you are using?

Andrew

**Comment by intrinsically** [comment]
no response
